---
- hosts: controller
  become: True
  gather_facts: false

  roles:
    - {
      name: sources,
      sources: {
        yarn: {
          key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg',
          source: 'deb https://dl.yarnpkg.com/debian/ stable main'
        }
      }
    }
    - {
      name: apt-packages,
      packages: [
        'curl',
        'nodejs',
        'yarn',
      ],
    }

  tasks:
    - name: Make sure dist folder exists
      file:
        path: ../dist
        state: directory
      tags: ['setup']

    - name: check for previous build
      shell: ls -1 ../dist
      register: build_files
      tags: ['setup']

    - name:
      file:
        path: ../dist/{{item}}
        state: absent
      with_items: "{{ build_files.stdout_lines }}"
      when: build_files.stdout_lines
      tags: ['setup']

    - name: install node packages
      yarn:
        path: ../
        state: present
      tags: ['packages']

    - name: build slides
      command: yarn build
      tags: ['build']

    - name: build files exist
      file:
        path: '../dist/{{item}}'
        state: file
      with_items: [
        'index.html',
        'main.js'
      ]
      tags: ['check']
