---
- hosts: slides
  become: True
  gather_facts: false
  tasks:
    - name: create project dir
      file:
        path: /www/slides/
        state: directory
    - name: copy build files
      copy:
        src: ../dist/
        dest: /www/slides/
  roles:
    - {
      name: nginx,
      sites: {
        slides: {
          port: 80,
          root: '/www/slides'
        }
      }
    }
