---
- hosts: slides
  become: True
  gather_facts: false
  roles:
    - {
      name: nginx,
      sites: {
        slides: {
          port: 80,
          root: '/www/slides',
          build_files: '../dist/'
        }
      }
    }
